name: chatscreen
description: "A module of chat app"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Caros
      fonts:
        - asset: assets/fonts/cretype-Caros.otf
          weight: 400
        - asset: assets/fonts/cretype-Caros-Black.otf
          weight: 900
        - asset: assets/fonts/cretype-Caros-Black-Italic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/cretype-Caros-Bold.otf
          weight: 700
        - asset: assets/fonts/cretype-Caros-Bold-Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/cretype-Caros-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/cretype-Caros-ExtraBold-Italic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/cretype-Caros-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/cretype-Caros-ExtraLight-Italic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/cretype-Caros-Heavy.otf
          weight: 800
        - asset: assets/fonts/cretype-Caros-Heavy-Italic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/cretype-Caros-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/cretype-Caros-Light.otf
          weight: 300
        - asset: assets/fonts/cretype-Caros-Light-Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/cretype-Caros-Medium.otf
          weight: 500
        - asset: assets/fonts/cretype-Caros-Medium-Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/cretype-Caros-Thin.otf
          weight: 100
        - asset: assets/fonts/cretype-Caros-Thin-Italic.otf
          weight: 100
          style: italic
    - family: Circular-Std
      fonts:
        - asset: assets/fonts/circular-std-medium-500.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 400





